clc;close all;clear all;
run=[2014 2015 2017 2019];
run=[2017 2019];
for yearrun=1:length(run)
    year=num2str(run(yearrun))
%% add path
results_dir=['results/',num2str(year)];
if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end
addpath('basic_data_set');
addpath(results_dir);
addpath('program');
%% set data read path
DEMPath='basic_data_set\DEM\DEM_EX.tif';
DEMlatPath='basic_data_set\DEM\lat.mat';
DEMlonPath='basic_data_set\DEM\lon.mat';
shpPath='basic_data_set\Administrative_divisions\gadm36_CHN_2.shp';
EnteromorphaDir='basic_data_set\Enteromorpha';
OceanCurrentDir='basic_data_set\current';
WindDir='basic_data_set\wind';
TemperatureDir='basic_data_set\temperature';
GLTFile='basic_data_set\GLT_of_En_current_temperature_wind\GLT.mat';
landMask='basic_data_set\landmask\land.tif';
GOCITIFF='basic_data_set\GOCI';
%% set the parameters of the drift drive module
%.................................set the scope of the study area
loc=[400 1600 130 1000];
%.................................set simulation duration
timeloc=[1 70];
%.................................set the simulation stage of automatic
%optimization and adjustment of parameters
simPT=[2 3];
%.................................set the stage of the test simulation
sim2014=[3 4];
sim2015=[3 4];
sim2017=[4 5];
sim2019=[3 4];
sim=eval(['sim',year]);
%.................................set the storage path of simulation
%results
saveMainPath=results_dir;
%.................................set wind drift coefficient
wc=0.05; 
%..................................set growth interval
gi=2;
%% set the parameters of the initial target simulation module
%.................................set the number of objects generated by
%each real green tide point
rectnum=10;
%.................................set the size of the simulation object
rectsize=[1 50];
%.................................set the maximum number of covered objects
%in the same position
rectrepetition=1;
%................................set the density threshold of the green
%tide point within the scope of the object
rectdensity=0.8;
%.................................set the time node of the object
%simulation start node
simrect2014=[1 2 3 4];
simrect2015=[1 2 3 4];
simrect2017=[1 2 3 4 5];
simrect2019=[1 2 3 4];
simrect=eval(['simrect',year]);
%% set the parameters of the generation and elimination module
%..................................................温度影响因子模块参数
%.........最大生长速率
Gmax=0.4;
%.........最大死亡速率
Dmax=0.1;
%.........最适宜生长温度下限
T1=15;
%.........最适宜生长温度上限
T2=20;
%.............生长温度极值
T3=25;
a1=1.15;
a2=1.8;
a3=1.1;
%%  read basic data
 [dataEnImg,EnNum,dataNwave,dataEwave,dataNwind,dataEwind,Temperature,...
     GLTlon,GLTlat,land,DEMPlot,DEMlat,DEMlon,Map]=...
     ReadBasicData(DEMPath,DEMlatPath,DEMlonPath,shpPath,EnteromorphaDir,...
     OceanCurrentDir,WindDir,TemperatureDir,GLTFile,landMask,...
     year,loc,timeloc);
%% run the initial object simulation module
close all;clc
saverect2path=InitialObjectSimulation(simrect,saveMainPath,dataEnImg,rectnum,...
    rectsize,rectdensity,rectrepetition,land,year);
%% Calculate the net growth rate
TempteratureIndex=CalculateNetGrowthRate(Gmax,Dmax,T1,T2,T3,a1,a2,a3,Temperature);
%% Run drift drive module with generation and elimination module
[savefile1]=DriftDrive(saverect2path,dataNwave,dataEwave,dataNwind,dataEwind,TempteratureIndex,sim,EnNum,year,wc,gi, results_dir);
%% Run drift drive module without generation and elimination module
[savefile2,savefileObjectTrajectory]=DriftDriveWithoutGE(saverect2path,dataNwave,dataEwave,dataNwind,dataEwind,sim,EnNum,year,wc,gi,results_dir);
%% Run drift drive only with pixels
savefile3=DriftDriveWithPixels(dataEnImg,dataNwave,dataEwave,dataNwind,dataEwind,sim,EnNum,year,wc,gi,results_dir);
%% read simulation results
RECTtrue=readRECTtrue(saverect2path,sim,year);
[RECT1,RECT2,Pixels]=ReadResultData(savefile1,savefile2,savefile3);
%% Convert simulation objects to pixels
RECT1=ConObjectstoPixels(RECT1);
RECT2=ConObjectstoPixels(RECT2);
RECTtrue=ConObjectstoPixels(RECTtrue);
%% edge extraction
clc;close all
shp1path=EdgeExtraction(RECT1,GLTlat,GLTlon,1,year,results_dir);
shp2path=EdgeExtraction(RECT2,GLTlat,GLTlon,2,year,results_dir);
shptruepath=EdgeExtraction(RECTtrue,GLTlat,GLTlon,4,year,results_dir);
shpPixel3path=EdgeExtraction(Pixels,GLTlat,GLTlon,3,year,results_dir);
shpPixelstruepath=EdgeExtraction(dataEnImg,GLTlat,GLTlon,5,year,results_dir);
waveLinepath=EdgeExtractionWave(dataNwave,GLTlat,GLTlon,year,results_dir);
%% visualization of results and statistical results accuracy
clc;close all
VS(GLTlat,GLTlon,Map,shp1path,shp2path,shpPixel3path,shptruepath,shpPixelstruepath,EnNum,sim,year,RECT1,RECT2,RECTtrue,Pixels,waveLinepath,GOCITIFF,dataEnImg,loc,results_dir);
end